### ISSUE TITLE
Hash from database?

### ISSUE THREAD

**Issue by ghost** [0x6470/bitwarden2hashcat#4]
Hi

Your tool works great, thank you so much for your work!
I'm trying to recover a master password for a friend which is stored in the database because we lost the data.json. We already did extract the hash from the database and convert it so that it gets accepted by hashcat. But It doesn't work because apparently the hash is [salted an dhashed again](https://bitwarden.com/help/what-encryption-is-used/#:~:text=Once%20a%20Bitwarden%20server%20receives%20the%20hashed%20password%2C%20it%20is%20salted%20again%20with%20a%20cryptographically%20secure%20random%20value%2C%20hashed%20again%2C%20and%20stored%20in%20our%20database) before being stored in the database. It does not match the hash from the data.json (on a test account)
Do you have any Idea how I can bring hashcat to also do the second hashing and salting?
Any inputs would be very welcome, we're really hitting a brick wall here...

Best Stephan

**Comment by 0x6470** [comment]
Hey Stephan,

thanks for your issue.
Unfortunately, the Bitwarden team is not known for keeping their documentation up to date continuously. For example, the default client-side iteration count is 100,002 at least since March 2021.
Their PoC page on the other hand is usually up to date.
Could you maybe verify with your test account if the hash you find in the database appears somewhere on this page: 
https://bitwarden.com/crypto.html
